version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: swiggy_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swiggy_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  swiggy-backend:
    build: .
    container_name: swiggy_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      # This tells Spring Boot to load application-docker.yml
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  mysql_data: